
package net.dlyt.qyds.web.service.erp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * @param vipPoint
     * @param key
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "VIPUsedUpdate", action = "http://tempuri.org/VIPUsedUpdate")
    @WebResult(name = "VIPUsedUpdateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VIPUsedUpdate", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.VIPUsedUpdate")
    @ResponseWrapper(localName = "VIPUsedUpdateResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.VIPUsedUpdateResponse")
    public String vipUsedUpdate(
            @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
                    String key,
            @WebParam(name = "VipPoint", targetNamespace = "http://tempuri.org/")
                    BaseDate vipPoint);

    /**
     * @param goods
     * @param key
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "GoodsUpdate", action = "http://tempuri.org/GoodsUpdate")
    @WebResult(name = "GoodsUpdateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GoodsUpdate", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.GoodsUpdate")
    @ResponseWrapper(localName = "GoodsUpdateResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.GoodsUpdateResponse")
    public String goodsUpdate(
            @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
                    String key,
            @WebParam(name = "Goods", targetNamespace = "http://tempuri.org/")
                    BaseDate goods);

    /**
     * @param vip
     * @param key
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "VIPUpdate", action = "http://tempuri.org/VIPUpdate")
    @WebResult(name = "VIPUpdateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VIPUpdate", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.VIPUpdate")
    @ResponseWrapper(localName = "VIPUpdateResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.VIPUpdateResponse")
    public String vipUpdate(
            @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
                    String key,
            @WebParam(name = "Vip", targetNamespace = "http://tempuri.org/")
                    BaseDate vip);

    /**
     * @param vipPoint
     * @param key
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "VIPPointUpdate", action = "http://tempuri.org/VIPPointUpdate")
    @WebResult(name = "VIPPointUpdateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VIPPointUpdate", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.VIPPointUpdate")
    @ResponseWrapper(localName = "VIPPointUpdateResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.VIPPointUpdateResponse")
    public String vipPointUpdate(
            @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
                    String key,
            @WebParam(name = "VipPoint", targetNamespace = "http://tempuri.org/")
                    BaseDate vipPoint);

    /**
     * @param key
     * @param order
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SaleInput", action = "http://tempuri.org/SaleInput")
    @WebResult(name = "SaleInputResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaleInput", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.SaleInput")
    @ResponseWrapper(localName = "SaleInputResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.SaleInputResponse")
    public String saleInput(
            @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
                    String key,
            @WebParam(name = "Order", targetNamespace = "http://tempuri.org/")
                    Orders order);

    /**
     * @param key
     * @param order
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "ReturnInput", action = "http://tempuri.org/ReturnInput")
    @WebResult(name = "ReturnInputResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReturnInput", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.ReturnInput")
    @ResponseWrapper(localName = "ReturnInputResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.ReturnInputResponse")
    public String returnInput(
            @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
                    String key,
            @WebParam(name = "Order", targetNamespace = "http://tempuri.org/")
                    Orders order);

    /**
     * @param coupon
     * @param key
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "CouponissueUpdate", action = "http://tempuri.org/CouponissueUpdate")
    @WebResult(name = "CouponissueUpdateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CouponissueUpdate", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.CouponissueUpdate")
    @ResponseWrapper(localName = "CouponissueUpdateResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.CouponissueUpdateResponse")
    public String couponissueUpdate(
            @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
                    String key,
            @WebParam(name = "Coupon", targetNamespace = "http://tempuri.org/")
                    Coupon coupon);

    /**
     * @param coupon
     * @param key
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "CouponSendUpdate", action = "http://tempuri.org/CouponSendUpdate")
    @WebResult(name = "CouponSendUpdateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CouponSendUpdate", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.CouponSendUpdate")
    @ResponseWrapper(localName = "CouponSendUpdateResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.CouponSendUpdateResponse")
    public String couponSendUpdate(
            @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
                    String key,
            @WebParam(name = "Coupon", targetNamespace = "http://tempuri.org/")
                    Coupon coupon);

    /**
     * @param coupon
     * @param key
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "CouponUsedUpdate", action = "http://tempuri.org/CouponUsedUpdate")
    @WebResult(name = "CouponUsedUpdateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CouponUsedUpdate", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.CouponUsedUpdate")
    @ResponseWrapper(localName = "CouponUsedUpdateResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.CouponUsedUpdateResponse")
    public String couponUsedUpdate(
            @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
                    String key,
            @WebParam(name = "Coupon", targetNamespace = "http://tempuri.org/")
                    Coupon coupon);

    /**
     * @param banks
     * @param key
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "BankUpdate", action = "http://tempuri.org/BankUpdate")
    @WebResult(name = "BankUpdateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BankUpdate", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.BankUpdate")
    @ResponseWrapper(localName = "BankUpdateResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.BankUpdateResponse")
    public String bankUpdate(
            @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
                    String key,
            @WebParam(name = "Banks", targetNamespace = "http://tempuri.org/")
                    Banktransfer banks);

    /**
     * @param exeType
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "ServerUpdateExe", action = "http://tempuri.org/ServerUpdateExe")
    @WebResult(name = "ServerUpdateExeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ServerUpdateExe", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.ServerUpdateExe")
    @ResponseWrapper(localName = "ServerUpdateExeResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.ServerUpdateExeResponse")
    public String serverUpdateExe(
            @WebParam(name = "ExeType", targetNamespace = "http://tempuri.org/")
                    String exeType);

    /**
     * @param sms
     * @return returns net.dlyt.qyds.web.service.erp.SmsResult
     */
    @WebMethod(operationName = "SendSms", action = "http://tempuri.org/SendSms")
    @WebResult(name = "SendSmsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSms", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.SendSms")
    @ResponseWrapper(localName = "SendSmsResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.SendSmsResponse")
    public SmsResult sendSms(
            @WebParam(name = "Sms", targetNamespace = "http://tempuri.org/")
                    SmsSend sms);

    /**
     * @param yto
     * @param key
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "YTOUpdate", action = "http://tempuri.org/YTOUpdate")
    @WebResult(name = "YTOUpdateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "YTOUpdate", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.YTOUpdate")
    @ResponseWrapper(localName = "YTOUpdateResponse", targetNamespace = "http://tempuri.org/", className = "net.dlyt.qyds.web.service.erp.YTOUpdateResponse")
    public String YTOUpdate(
            @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
                    String key,
            @WebParam(name = "YTOs", targetNamespace = "http://tempuri.org/")
                    YTO yto
    );

}
